version: '3.1'

services:

  friends_db:
    image: postgres:9.6.5-alpine
    restart: always
    ports:
      - 5685:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: iamgroot
      POSTGRES_DB: extractor_db
    container_name: extractor_db